allowBuilds:
  '@clerk/shared': true
  bufferutil: true
  core-js: true
  esbuild: true
  msw: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true
  workerd: true
onlyBuiltDependencies:
  - '@clerk/shared'
  - bufferutil
  - core-js
  - esbuild
  - msw
  - sharp
  - unrs-resolver
  - utf-8-validate
  - workerd
