/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DesignInspirationRouteImport } from './routes/design-inspiration'
import { Route as IndexRouteImport } from './routes/index'

const DesignInspirationRoute = DesignInspirationRouteImport.update({
  id: '/design-inspiration',
  path: '/design-inspiration',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design-inspiration': typeof DesignInspirationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design-inspiration': typeof DesignInspirationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design-inspiration': typeof DesignInspirationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/design-inspiration'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/design-inspiration'
  id: '__root__' | '/' | '/design-inspiration'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignInspirationRoute: typeof DesignInspirationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/design-inspiration': {
      id: '/design-inspiration'
      path: '/design-inspiration'
      fullPath: '/design-inspiration'
      preLoaderRoute: typeof DesignInspirationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignInspirationRoute: DesignInspirationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
